version: '3.7'
services:
    nodejs-mywhats:
        # build: node:14-slim
        build:
            context: .
            dockerfile: ./Dockerfile
        image: "node:14-slim"
        container_name: nodejs-mywhats
        volumes:
          - ./server/nginx.conf:/etc/nginx/nginx.conf
        container_name: nodejs-mywhats
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ./src:/usr/src/app
        links:
            - nginx
    nginx:
        build: Nginx
        volumes:
            - ./server/nginx.conf:/etc/nginx/nginx.conf
        container_name: nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        links:
            - nodejs-mywhats